# Generated by Django 4.2.3 on 2023-07-20 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('do_list', '0002_to_do_list_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_list',
            name='borrower',
        ),
        migrations.AddField(
            model_name='to_do_list',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL),
        ),
    ]
