# Generated by Django 4.2.3 on 2023-07-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0003_remove_to_do_list_borrower_to_do_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='name_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
            ],
        ),
    ]
