# Generated by Django 4.2.3 on 2023-07-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0004_name_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name_list',
        ),
        migrations.RemoveField(
            model_name='to_do_list',
            name='user',
        ),
    ]
