# Generated by Django 4.2.3 on 2023-07-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0005_delete_name_list_remove_to_do_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='name_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='to_do_list',
            name='user_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='do_list.name_list'),
        ),
    ]
