# Generated by Django 4.2.3 on 2023-07-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0006_name_list_to_do_list_user_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='particular_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_list', models.CharField(max_length=50)),
                ('specific_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='do_list.to_do_list')),
            ],
        ),
    ]
