# Generated by Django 4.2.3 on 2023-07-22 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('do_list', '0008_alter_particular_list_specific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='user_names_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
