# Generated by Django 4.2.3 on 2023-07-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0009_to_do_list_user_names_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='particular_list',
            name='specific_name',
        ),
        migrations.RemoveField(
            model_name='to_do_list',
            name='user_names',
        ),
    ]
